### ISSUE TITLE
select max(date) from

### ISSUE THREAD

**Issue by meeximum** [EvidentSolutions/dalesbred#47]
Hi,

how can I do a select with an aggregate function? I want to return the max date of a column in a table?

regards
Markus

**Comment by komu** [comment]
Hi,

This has nothing to do with Dalesbred per se, Dalesbred just passes the query to database and then maps the results to your classes in a very straightforward way.

Do you have a query that you can execute directly using database console, but causes problems with Dalesbred for some reason?

**Comment by meeximum** [comment]
Hi,

I tried to run this statement
`Optional<Date> transDate = db.findOptional(Date.class, "SELECT MAX(trans_date) FROM items");`

and get this stack trace
`org.dalesbred.internal.instantiation.InstantiationFailureException: could not find a way to instantiate class java.sql.Date with parameters [MAX(trans_date): java.sql.Timestamp] (query: SELECT MAX(trans_date) FROM items [])
	at org.dalesbred.internal.instantiation.InstantiatorProvider.lambda$findInstantiator$2(InstantiatorProvider.java:119)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.dalesbred.internal.instantiation.InstantiatorProvider.findInstantiator(InstantiatorProvider.java:119)
	at org.dalesbred.internal.instantiation.InstantiatorProvider.findInstantiator(InstantiatorProvider.java:95)
	at org.dalesbred.internal.result.InstantiatorRowMapper.mapRow(InstantiatorRowMapper.java:65)
	at org.dalesbred.result.RowMapper.lambda$optional$2(RowMapper.java:87)
	at org.dalesbred.Database.lambda$executeQuery$0(Database.java:285)
	at org.dalesbred.transaction.DefaultTransaction.execute(DefaultTransaction.java:51)
	at org.dalesbred.transaction.DefaultTransactionManager.withNewTransaction(DefaultTransactionManager.java:59)
	at org.dalesbred.transaction.AbstractTransactionManager.withTransaction(AbstractTransactionManager.java:61)
	at org.dalesbred.Database.withTransaction(Database.java:199)
	at org.dalesbred.Database.withTransaction(Database.java:188)
	at org.dalesbred.Database.withTransaction(Database.java:160)
	at org.dalesbred.Database.withCurrentTransaction(Database.java:262)
	at org.dalesbred.Database.executeQuery(Database.java:276)
	at org.dalesbred.Database.findOptional(Database.java:397)
	at org.dalesbred.Database.findOptional(Database.java:407)
	at hogast.Dalesbreed.test(Dalesbreed.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)`

so I thought findOptional is the wrong way to obtain one single value :-/

**Comment by meeximum** [comment]
got it, I tried with java.sql.Date, but I have to use java.util.Date, now it works fine, thx

**Comment by komu** [comment]
Right. Or, even better, you can use `java.time.Instant`. It should work out-of-the-box without any extra configuration.
