### ISSUE TITLE
stange NullP

### ISSUE THREAD

**Issue by plandem** [EvidentSolutions/dalesbred#8]
When i'm trying to use findUniqueOrNull, but nothing back from DB, i got 'java.lang.NullPointerException'.
I use it as:

```
db.findUniqueOrNull(model.getClass(), query);
```

where class is: 

```
com.luxms.core.model.Location
```

and here is query:

```
SELECT loc_id, parent_id, longitude, latitude, level, is_point, title FROM locations WHERE title = ? AND level = ? AND parent_id IS NULL [Корень, 0]
```

Here is stacktrace

```
java.lang.NullPointerException
    at com.luxms.core.importer.Importer.resolveModel(Importer.java:73)
    at com.luxms.core.db.IModelBI.save(IModelBI.java:53)
    at com.luxms.app.Main.lambda$importLocations$2(Main.java:125)
    at com.luxms.app.Main$$Lambda$58/220695851.accept(Unknown Source)
    at java.util.HashMap.forEach(HashMap.java:1280)
    at com.luxms.app.Main.importLocations(Main.java:123)
    at com.luxms.app.Main.main(Main.java:76)
```

version 1.0.0-aplha2

**Comment by plandem** [comment]
sorry i close it. it was actually mine bug.
